git add lib/core/logic/haptics.dart; git commit -m "chore: initialize production-grade haptics engine for UI feedback"
git add lib/core/logic/security.dart; git commit -m "feat: implement SHA-256 cryptographic hashing for production hardening"
git add lib/core/providers.dart; git commit -m "feat: add global authProvider for session-based security"
git add lib/features/auth/auth_screen.dart; git commit -m "feat: implement secure AuthScreen with hashed PIN verification"
git add lib/core/router.dart; git commit -m "refactor: migrate GoRouter to reactive routerProvider with security guards"
git add lib/main.dart; git commit -m "fix: restore app-wide routing guard and PIN lockout"
git add lib/features/stock_in/delivery_controller.dart; git commit -m "feat: expand DeliveryCartItem model with unit selling prices"
git add lib/features/stock_in/new_delivery_screen.dart; git commit -m "feat: implement automatic product identification and scanner auto-fill"
git add lib/features/stock_in/widgets/item_edit_dialog.dart; git commit -m "feat: add ItemEditDialog for quantity and price confirmation"
git add lib/core/database/seed_data.dart; git commit -m "feat: expand guessCategory regex engine with 50+ new Filipino brand keywords"
git add lib/core/database/tables.dart; git commit -m "feat: add Noodles category and unit tracking to database schema"
git add lib/features/dashboard/dashboard_providers.dart; git commit -m "logic: harden lowStockItemsProvider to eliminate false-positive alerts on seeded data"
git add lib/features/reports/audit_log_screen.dart; git commit -m "feat: implement AuditLogFormatter for human-readable system narratives"
git add lib/features/reports/reports_controller.dart; git commit -m "feat: implement detailed financial analytics for inventory performance"
git add lib/features/reports/reports_screen.dart; git commit -m "ui: overhaul ReportsScreen with detailed analytics cards and store value metrics"
git add lib/features/settings/settings_controller.dart; git commit -m "feat: add StoreNameNotifier for personalized store branding"
git add lib/features/settings/settings_screen.dart; git commit -m "ui: implement personalized settings and security management"
git add lib/features/inventory/product_list_screen.dart; git commit -m "feat: implement ProductListScreen for managed inventory browsing"
git add lib/features/dashboard/dashboard_screen.dart; git commit -m "ui: enhance dashboard with predictive stock alerts and activity feeds"
git add lib/features/count/count_controller.dart; git commit -m "feat: implement physical count discrepancy logic and audit logging"
git add lib/features/count/count_list_screen.dart; git commit -m "ui: implement count history and draft management"
git add lib/features/count/new_count_screen.dart; git commit -m "ui: implement interactive physical count scanner flow"
git add lib/core/logic/background_tasks.dart; git commit -m "chore: optimize background audit engine and system heartbeat logging"
git add pubspec.yaml; git commit -m "chore: update dependencies and production assets"
git push origin main
